import jsPDF from "jspdf";
import "jspdf-autotable";

export const generateReportCardPDF = (studentData, termResults, marks, schoolLogoUrl) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // 1. Header & Logo
    if (schoolLogoUrl) {
        // Since we can't easily fetch and convert to base64 in a generic way here,
        // we'll use a placeholder or assume it's pre-loaded if possible.
        // For now, let's just draw text.
    }

    doc.setFontSize(22);
    doc.setTextColor(0, 51, 102);
    doc.text("JUDITH CHRISTIAN SCHOOL", pageWidth / 2, 20, { align: "center" });

    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text("Official Academic Report Card", pageWidth / 2, 30, { align: "center" });
    doc.line(20, 35, pageWidth - 20, 35);

    // 2. Student Info
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Student Name: ${studentData.fullName}`, 20, 45);
    doc.text(`Admission No: ${studentData.admissionNo}`, 20, 52);
    doc.text(`Class: ${studentData.class}`, pageWidth - 70, 45);
    doc.text(`Term: ${termResults.term}`, pageWidth - 70, 52);

    // 3. Subject Marks Table
    const tableData = marks.map(m => [m.subject, m.score, m.grade || "N/A"]);

    doc.autoTable({
        startY: 60,
        head: [['Subject', 'Score', 'Grade']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillStyle: [0, 51, 102], textColor: 255 },
        margin: { left: 20, right: 20 }
    });

    const finalY = doc.lastAutoTable.finalY + 10;

    // 4. Summary Statistics
    doc.setFontSize(12);
    doc.text(`Total Score: ${termResults.totalScore}`, 20, finalY);
    doc.text(`Average Score: ${termResults.averageScore.toFixed(2)}`, 20, finalY + 7);
    doc.text(`Overall Grade: ${termResults.grade}`, pageWidth - 70, finalY);
    doc.text(`Class Position: ${termResults.position}`, pageWidth - 70, finalY + 7);

    // 5. Comments
    if (studentData.comments && studentData.comments.length > 0) {
        const comment = studentData.comments[studentData.comments.length - 1].text;
        doc.setFontSize(11);
        doc.setFont("helvetica", "italic");
        doc.text("Teacher's Remarks:", 20, finalY + 20);
        doc.setFont("helvetica", "normal");
        doc.text(comment, 20, finalY + 27, { maxWidth: pageWidth - 40 });
    }

    // 6. Signatures
    const sigY = finalY + 50;
    doc.line(20, sigY, 80, sigY);
    doc.text("Class Teacher", 35, sigY + 7);

    doc.line(pageWidth - 80, sigY, pageWidth - 20, sigY);
    doc.text("Principal", pageWidth - 65, sigY + 7);

    // 7. Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Digitally Generated by JSMS", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

    // Save
    doc.save(`Report_Card_${studentData.admissionNo}_${termResults.term}.pdf`);
};
